logging:
  level:
    org.springframework.data.mongodb: INFO
    org.springframework.security: INFO
    org.springframework.session: INFO

server:
  error:
    path: "/error"
  server-header:
  servlet:
    context-path: /manage/api
    session:
      timeout: 28800
      cookie:
        secure: true

features: push, validation, push_preview, orphans, find_my_data, edugain, auto_refresh, bogus
base_domain: test2.surfconext.nl
environment: prod

push:
  eb:
    url: http://localhost:9898/api/connections
    name: OpenConext EngineBlock
    user: user
    password: password
    exclude_edugain_imports: true
    exclude_oidc_rp: false
  oidc:
    url: http://localhost:9898/manage/connections
    user: manage
    name: OpenConext OIDC-NG
    password: secret
    enabled: true

product:
  name: Manage
  organization: OpenConext
  #  service_provider_feed_url: http://mds.edugain.org/edugain-v2.xml
  service_provider_feed_url: http://localhost:8000/edugain.xml
  supported_languages: en,nl
  show_oidc_rp: true

metadata_configuration_path: classpath:/metadata_configuration
metadata_templates_path: classpath:/metadata_templates
metadata_export_path: classpath:/metadata_export

security:
  backdoor_user_name: backdoor
  backdoor_password: secret
  api_users_config_path: classpath:/manage-api-users.yml
  super_user_team_names: urn:collab:group:test.surfteams.nl:nl:surfnet:diensten:manage_super_users, urn:collab:group:test.surfteams.nl:nl:surfnet:diensten:manage_super_users_2

crypto:
  development-mode: True
  public-key-location: classpath:nope
#  development-mode: False
#  public-key-location: classpath:/invite_public_key.pem

oidc:
  user: manage
  password: secret
  url: https://oidc.test2.surfconext.nl/oidc/api/clients
  feature: false
  acsLocation: https://oidc.test2.surfconext.nl/saml/SSO

spring:
  mail:
    host: localhost
    port: 3025
  data:
    mongodb:
      uri: mongodb://localhost:27017/metadata_test
  datasource:
    url: jdbc:mysql://localhost/pdpserver?autoReconnect=true&useSSL=false
    username: root
    password:
    driverClassName: org.mariadb.jdbc.Driver

  main:
    banner-mode: "off"

cookie:
  secure: false
  # Options are 'Strict', 'Lax' or 'None'
  same_site: None

# We disable all endpoints except health for the load-balancer and info for git information.
management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "health,info"
      base-path: "/internal"
  endpoint:
    info:
      enabled: true
  info:
    git:
      mode: full

gui:
  disclaimer:
    background-color: red
    content: LOCAL

metadata_import:
  auto_refresh:
    cronSchedule: "-"

cron:
  node-cron-job-responsible: True

# used by the git plugin
info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"
